name: Download, unpack and commit the solution to git
run-name: Getting ${{ github.event.inputs.solution_name }} from pipelines host environment and committing
on:
  workflow_dispatch:
    inputs:
      environment_url:
        description: "The url of the Dataverse environment to export solution"
        required: true
      solution_name:
        description: "Name of the Solution in Dataverse environment"
        required: true
      solution_version:
        description: "Version of the Solution in Dataverse environment"
        required: true
      user_name: 
        description: "User name for the commit"
        required: true
      user_email: 
        description: "User email for the commit"
        required: true
      source_branch:
        description: "Branch for the solution commit"
        required: true
        default: main
      target_branch:
        description: "Branch to create for the solution commit"
        required: true
      commit_message:
        description: "Message to provide for the commit"
        required: true
permissions:
  contents: write
jobs:
  export-unpack-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.event.inputs.source_branch }}

      - name: Install Power Platform Build Tools
        uses: microsoft/powerplatform-actions/actions-install@v0

      - name: Verify Service Connection
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          app-id: ${{secrets.CLIENT_ID}}
          client-secret: ${{secrets.CLIENT_SECRET}}
          tenant-id: ${{secrets.TENANT_ID}}
          environment-url: "${{ github.event.inputs.environment_url }}"

      - name: Create or Checkout branch ${{ github.event.inputs.target_branch }}
        shell: pwsh
        run: |
          $branchToFind = "${{ github.event.inputs.target_branch }}"
          $branches = git branch -a
          if ([System.String]::Join("",$branches).Contains($branchToFind)) {
            echo "checking out $branchToFind"
            git checkout  $branchToFind
            git pull
          }
          else {
            git init
            git checkout -b ${{ github.event.inputs.target_branch }} ${{ github.event.inputs.source_branch }}
          }

      - name: Export Unmanaged Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: "${{ github.event.inputs.environment_url }}"
          app-id: ${{secrets.CLIENT_ID}}
          client-secret: ${{secrets.CLIENT_SECRET}}
          tenant-id: ${{secrets.TENANT_ID}}
          solution-name: "${{ github.event.inputs.solution_name }}"
          solution-output-file: "Solutions/${{ github.event.inputs.solution_version }}/${{ github.event.inputs.solution_name }}_unmanaged.zip"
          managed: false
          overwrite: true

      - name: Run Power Platform Checker
        uses: microsoft/powerplatform-actions/check-solution@v0
        with:
          environment-url: "${{ github.event.inputs.environment_url }}"
          app-id: ${{secrets.CLIENT_ID}}
          client-secret: ${{secrets.CLIENT_SECRET}}
          tenant-id: ${{secrets.TENANT_ID}}
          path: "Solutions/${{ github.event.inputs.solution_version }}/${{ github.event.inputs.solution_name }}_unmanaged.zip"
          geo: "australia"
          checker-logs-artifact-name: "CheckSolutionLogs"

      - name: Unpack Unmanaged Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: "Solutions/${{ github.event.inputs.solution_version }}/${{ github.event.inputs.solution_name }}_unmanaged.zip"
          solution-folder: "src/${{ github.event.inputs.solution_name }}"
          solution-type: 'Unmanaged'
          process-canvas-apps: true
          overwrite-files: true

      - name: Export Managed Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: "${{ github.event.inputs.environment_url }}"
          app-id: ${{secrets.CLIENT_ID}}
          client-secret: ${{secrets.CLIENT_SECRET}}
          tenant-id: ${{secrets.TENANT_ID}}
          solution-name: "${{ github.event.inputs.solution_name }}"
          solution-output-file: "Solutions/${{ github.event.inputs.solution_version }}/${{ github.event.inputs.solution_name }}_managed.zip"
          managed: true
          overwrite: true

      - name: Commit changes to branch ${{ github.event.inputs.target_branch }}
        shell: pwsh
        run: |
          git config user.name "Gerald de Run"
          git config user.email "gderun@hotmail.com"
          git pull 
          git add --all
          git pull 
          git commit -am "${{ github.event.inputs.commit_message }}" --allow-empty

      - name: Push changes to branch ${{ github.event.inputs.target_branch }}
        shell: pwsh
        run: |
          git push origin ${{ github.event.inputs.target_branch }}
